# Generated by Django 3.1.7 on 2021-08-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('origin', models.CharField(max_length=60)),
                ('process', models.CharField(max_length=60)),
                ('roast_profile', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('1', 'Rituals'), ('2', 'Ventures'), ('3', 'Horizons')], default='1', max_length=20)),
                ('traceability', models.CharField(max_length=60)),
                ('is_house', models.BooleanField(default=True)),
                ('is_guest', models.BooleanField(default=False)),
            ],
        ),
    ]
