# Generated by Django 3.1.7 on 2021-08-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='cultivar',
            field=models.CharField(default='cultivar_1', max_length=60),
        ),
    ]
