# Generated by Django 3.1.7 on 2021-08-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_auto_20210821_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='espresso',
            name='extraction_time',
            field=models.CharField(default='26-28', max_length=10),
        ),
    ]
