# Generated by Django 3.1.7 on 2021-08-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_espresso_extraction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espresso',
            name='dry_weight',
            field=models.DecimalField(decimal_places=1, default=18.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='espresso',
            name='wet_weight',
            field=models.IntegerField(default=36),
        ),
    ]
