# Generated by Django 3.1.7 on 2021-08-25 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_auto_20210825_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=8)),
                ('method', models.CharField(choices=[('Batch', 'Batch'), ('v60', 'v60')], default='Batch', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_temperature', models.DecimalField(decimal_places=0, max_digits=2)),
                ('water_tds', models.DecimalField(decimal_places=1, max_digits=3)),
                ('grind_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('recipe', models.TextField()),
                ('acidity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)])),
                ('acidity_quality', models.CharField(choices=[('Delicate', 'Delicate'), ('Mild', 'Mild'), ('Nippy', 'Nippy'), ('Piquant', 'Piquant'), ('Sweet', 'Sweet'), ('Tangy', 'Tangy'), ('Tart', 'Tart'), ('Lemon', 'Lemon'), ('Vibrant', 'Vibrant'), ('Grassy', 'Grassy'), ('Hard', 'Hard'), ('Soft', 'Soft'), ('Sour', 'Sour'), ('Winey', 'Winey'), ('Grapefruit', 'Grapefruit')], default='Delicate', max_length=15)),
                ('aroma', models.CharField(choices=[('Berry', 'Berry'), ('Floral', 'Floral'), ('Fruity', 'Fruity'), ('Caramel', 'Caramel'), ('Resinous', 'Resinous'), ('Lemon', 'Lemon'), ('Grapefruit', 'Grapefruit'), ('Chocolate', 'Chocolate'), ('Spicy', 'Spicy'), ('Earthy', 'Earthy'), ('Nutty', 'Nutty'), ('Malty', 'Malty'), ('Carbonic', 'Carbonic'), ('Pepper', 'Pepper'), ('Vanilla', 'Vanilla'), ('Hidy', 'Hidy'), ('Musty', 'Musty'), ('Leather', 'Leather'), ('Butter', 'Butter'), ('Toast', 'Toast'), ('Smoke', 'Smoke')], default='Berry', max_length=15)),
                ('flavour_score', models.FloatField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(10)])),
                ('flavour_quality', models.CharField(choices=[('Sweet', 'Sweet'), ('Sour', 'Sour'), ('Salt', 'Salt'), ('Delicate', 'Delicate'), ('Rich', 'Rich'), ('Intense', 'Intense'), ('Pungent', 'Pungent'), ('Musty', 'Musty'), ('Pest-Crop', 'Pest-Crop'), ('Woody', 'Woody'), ('Flat', 'Flat'), ('Greenish', 'Greenish'), ('Fruity', 'Fruity'), ('Balanced', 'Balanced'), ('Exotic', 'Exotic'), ('Chocolate', 'Chocolate'), ('Spicy', 'Spicy'), ('Nutty', 'Nutty')], default='Sweet', max_length=15)),
                ('texture', models.CharField(choices=[('Low', 'Low'), ('Low-Medium', 'Low-Medium'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], default='Medium', max_length=15)),
                ('texture_quality', models.CharField(choices=[('Buttery', 'Buttery'), ('Creamy', 'Creamy'), ('Smooth', 'Smooth'), ('Rich', 'Rich'), ('Velvety', 'Velvety'), ('Watery', 'Watery'), ('Oily', 'Oily'), ('Dry', 'Dry'), ('Chalky', 'Chalky'), ('Gritty', 'Gritty'), ('Rough', 'Rough'), ('Astringent', 'Astringent'), ('Metallic', 'Metallic')], default='Velvety', max_length=15)),
                ('balance', models.CharField(choices=[('Low', 'Low'), ('Low-Medium', 'Low-Medium'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], default='Medium', max_length=15)),
                ('sweetness', models.CharField(choices=[('Low', 'Low'), ('Low-Medium', 'Low-Medium'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], default='Medium', max_length=15)),
                ('bitterness', models.CharField(choices=[('Low', 'Low'), ('Low-Medium', 'Low-Medium'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], default='Medium', max_length=15)),
                ('body', models.CharField(choices=[('Low', 'Low'), ('Low-Medium', 'Low-Medium'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], default='Medium', max_length=15)),
                ('finish', models.CharField(choices=[('Short', 'Short'), ('Dry', 'Dry'), ('Bitter', 'Bitter'), ('Sour', 'Sour'), ('Harsh', 'Harsh'), ('Dirty', 'Dirty'), ('Clean', 'Clean'), ('Floral', 'Floral'), ('Fruity', 'Fruity'), ('Lingering', 'Lingering'), ('Resonant', 'Resonant')], default='Lingering', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coffee_name', models.ForeignKey(limit_choices_to={'roast_profile': 'Filter'}, on_delete=django.db.models.deletion.CASCADE, related_name='filter_coffee_name', to='calibration.coffee')),
            ],
        ),
    ]
