# Generated by Django 3.1.7 on 2021-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='water_tds',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='filter',
            name='water_temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
