# Generated by Django 3.1.7 on 2021-09-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_espresso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_log_site', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='espresso',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='espresso_log_site', to=settings.AUTH_USER_MODEL),
        ),
    ]
