# Generated by Django 3.2.3 on 2021-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0011_auto_20210913_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
