# Generated by Django 3.1.7 on 2021-10-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0012_coffee_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espresso',
            name='water_tds',
            field=models.DecimalField(decimal_places=2, default=1.03, max_digits=3),
        ),
    ]
