# Generated by Django 3.1.7 on 2021-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_auto_20211019_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='water_tds',
            field=models.DecimalField(decimal_places=2, default=1.03, max_digits=3),
        ),
    ]
